# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noreen', '0005_img_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='value_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_10',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_11',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_12',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_13',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_14',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_15',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_16',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_17',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_18',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_19',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_20',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_21',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_22',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_23',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_24',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_25',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_26',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_27',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_28',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_29',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_30',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_7',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_8',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='value_9',
            field=models.IntegerField(default=-1),
        ),
    ]
